spring:
  servlet:
    multipart:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cmfrjfug1b2c73cotg10-a.frankfurt-postgres.render.com:5432/devlink_nk00
    username: lotarys
    password: J5kFofm30FN7PH3CD2KVTeTj2kGCHMXj
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
jwt:
  SECRET_KEY: 5007cbe87e2807243289f5cec99a57364348226c638e09d8dc008ae99e3918cd
yandex:
  token: ${YANDEX_TOKEN_VARIABLE}
logging:
  level:
    org.springframework: debug
