spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: {$username}
    password: {$password}
    url: {$url}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
jwt:
  SECRET_KEY: {$SECRET_KEY}

