spring:
  servlet:
    multipart:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
jwt:
  SECRET_KEY: 5007cbe87e2807243289f5cec99a57364348226c638e09d8dc008ae99e3918cd
yandex:
  token: y0_AgAAAABeuc4rAArFNAAAAAD3vDjKzCxAQbJwQMq5aB-RzzST3EAYMlo
logging:
  level:
    org.springframework: debug
