spring:
  servlet:
    multipart:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cl0luf48s0fs73eqp7v0-a.frankfurt-postgres.render.com:5432/devlink_mq8n
    username: lotarys
    password: Zk210mvlokaceqs6W8MP1XoDkP9Fyu9x
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
jwt:
  SECRET_KEY: 5007cbe87e2807243289f5cec99a57364348226c638e09d8dc008ae99e3918cd
yandex:
  token: y0_AgAAAABeuc4rAArFNAAAAADxHSiblzU0nbCVQ2WsQGWjWoWAvJ0oWbE
logging:
  level:
    org.springframework: debug
